services:
  #nextjs service
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./next_app
      dockerfile: next.dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_API_URL=http://flaskapi:4000
    depends_on:
      db:
        condition: service_started
      flaskapi:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./next_app/prisma:/app/prisma

  # flask service
  flaskapi:
    container_name: flask_api
    image: flaskapp:1.0.0
    build:
      context: ./flask_api
      dockerfile: flask.dockerfile
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - INDRA_API_KEY=${INDRA_API_KEY}
    restart: unless-stopped


# db service
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Add nginx service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - nextapp
      - flaskapi
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
